[package]
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
description = "DFU flash utility with GUI"
edition = "2018"
homepage = "https://github.com/sourcebox/dfu-buddy"
license = "MIT"
name = "dfu-buddy"
repository = "https://github.com/sourcebox/dfu-buddy"
rust-version = "1.56"
version = "0.1.0-alpha3"

[dependencies]
dfufile = "0.1"
dirs = "4.0"
eframe = {version = "0.16", features = ["persistence"]}
futures = "0.3"
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"]}
regex = "1.5"
rfd = "0.6"
rusb = {version = "0.9"}
serde = {version = "1", features = ["derive"]}
simple_logger = {version = "1.16", features = ["colors", "timestamps", "threads"]}

[features]
default = ["libusb-vendored"]
libusb-vendored = ["rusb/vendored"]

[profile.release]
lto = true

[package.metadata.bundle]
identifier = "de.sourcebox.dfu-buddy"
name = "DFU Buddy"
osx_minimum_system_version = "10.11"
