[package]
name = "dfu-buddy"
version = "0.1.0-alpha3"
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
license = "MIT"
edition = "2021"
rust-version = "1.60"
description = "DFU flash utility with GUI"
homepage = "https://github.com/sourcebox/dfu-buddy"
repository = "https://github.com/sourcebox/dfu-buddy"

[dependencies]
dfufile = "0.1"
dirs = "4.0"
futures = "0.3"
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"]}
regex = "1.5"
rfd = "0.8"
rusb = {version = "0.9"}
serde = {version = "1", features = ["derive"]}
simple_logger = {version = "2.1"}

[dependencies.eframe]
version = "0.18"
features = ["persistence"]

[features]
default = ["libusb-vendored"]
libusb-vendored = ["rusb/vendored"]

[profile.release]
lto = true
strip = true

[package.metadata.bundle]
identifier = "de.sourcebox.dfu-buddy"
name = "DFU Buddy"
osx_minimum_system_version = "10.11"
