[package]
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
description = "DFU flash utility with GUI"
edition = "2018"
homepage = "https://github.com/sourcebox/dfu-buddy"
license = "MIT"
name = "dfu-buddy"
repository = "https://github.com/sourcebox/dfu-buddy"
version = "0.1.0"

[dependencies]
dfufile = "0.1"
dirs = "3.0"
eframe = {git = "https://github.com/emilk/egui", rev = "906a798003ac301cd6733f4dbba0452c515ecb12", features = ["persistence"]}
futures = "0.3"
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"]}
regex = "1.5"
rfd = "0.4"
rusb = {version = "0.8", features = ["vendored"]}
serde = {version = "1", features = ["derive"], optional = true}
simple_logger = "1.11"

[patch.crates-io]
winit = {git = "https://github.com/PolyMeilex/winit ", branch = "master"}

[features]
default = ["persistence"]
persistence = ["eframe/persistence", "serde"]

[profile.release]
lto = true

[package.metadata.bundle]
identifier = "de.sourcebox.dfu-buddy"
name = "DFU Buddy"
osx_minimum_system_version = "10.11"
